name: Test Reporter
description: |
  Displays test results from popular testing frameworks directly in GitHub.
  Supports .NET (xUnit, NUnit, MSTest), Dart, Flutter and JavaScript (JEST).
author: Michal Dorner <dorner.michal@gmail.com>
inputs:
  annotations:
    description: Enables code annotations with error message and stack trace captured during test execution
    required: true
    default: 'true'
  fail-on-error:
    description: Set this action as failed if test report contain any failed test
    required: true
    default: 'true'
  name:
    description: Name of the check run
    required: true
  path:
    description: Path to test report
    required: true
  reporter:
    description: |
      Format of test report. Supported options:
        - dart-json
        - dotnet-trx
        - flutter-machine
        - jest-junit
    required: true
  token:
    description: GitHub Access Token
    required: false
    default: ${{ github.token }}
  working-directory:
    description: Relative path under $GITHUB_WORKSPACE where the repository was checked out
    required: false
outputs:
  conclusion:
    description: |
      Final conclusion of the created check run:
        - 'success' if no failed tests was found
        - 'failure' if any failed test was found
runs:
  using: 'node12'
  main: 'dist/index.js'
