name: 'Test Check Reporter'
description: |
  Presents test results from popular testing frameworks as Github check run.
  Supports:
    - dotnet (trx logger)
    - flutter (JSON output with '--machine' flag )
    - jest (jest-junit reporter)

author: 'Michal Dorner <dorner.michal@gmail.com>'
inputs:
  fail-on-error:
    description: 'Set this action as failed if test report contains any failed test'
    required: true
    default: 'true'
  name:
    description: 'Name of the check run'
    required: true
  path:
    description: 'Path to test report'
    required: true
  reporter:
    description: |
      Format of test report. Supported options:
        - dart-json
        - dotnet-trx
        - flutter-machine
        - jest-junit
    required: true
  token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
outputs:
  conclusion:
    description: |
      Final conclusion of the created check run:
        - 'success' if no failed tests was found
        - 'failure' if any failed test was found
runs:
  using: 'node12'
  main: 'dist/index.js'
