name: 'JUnit Check Report'
description: 'Presents results of junit test report as Github check run'
author: 'Michal Dorner <dorner.michal@gmail.com>'
inputs:
  token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'dist/index.js'
